### ISSUE TITLE
incorrect automatic bundle creation

### ISSUE THREAD

**Issue by MigRam** [cceh/ELDP-Environment-for-CMDI-Maker#11]
There is a conflict with the automatic bundle creation. CMDI Maker creates bundles with correct files, bundles with wav files and completely different text files, and bundles with text files only.

**Comment by fxru** [comment]
The issue occurs if you delete a file from the file list. In both the ELDP and the IMDI profile. The incorrect association of files to sessions will only arise for files with a higher ID than the deleted file in the resources list.

The effect seems to be slightly different in the two profiles.

I documented the different states of the IMDI-Profile by exporting cmp-files:

[cmp_files_wrong_session_association.zip](https://github.com/cceh/ELDP-Environment-for-CMDI-Maker/files/294751/cmp_files_wrong_session_association.zip)
