### ISSUE TITLE
Detection of mimeType from Import File Projects not working

### ISSUE THREAD

**Issue by MigRam** [cceh/ELDP-Environment-for-CMDI-Maker#12]
The mimeType detection when users imports a projectfile e.g. "CMDI-Maker-Project.cmp". Actually the mimeType of the file are detected as "undefined".

**Comment by jblumtritt** [comment]
There has been a change in the cmp-Format. please see screenshot attached.
The key for the filed was "type" until eldp v1.11 and then changed to "mimeType" in eldp 1.12.
![eldp-import-projects-mimtype-detection](https://cloud.githubusercontent.com/assets/3205396/15009863/489c50d8-11e9-11e6-8c8e-8e81104459c9.jpg)

**Comment by jblumtritt** [comment]
This issue has also been discussed internally 
- https://redmine.uni-koeln.de/issues/2828

**Comment by MigRam** [comment]
close #29
