### ISSUE TITLE
Values "Unkown" and "Unspecified" in "Continent" are not allowed and produce validation errors

### ISSUE THREAD

**Issue by jblumtritt** [cceh/ELDP-Environment-for-CMDI-Maker#17]
"Unspecified" and "Unkown" are not in the value scheme of "Continent" in projectGeographic:
https://catalog.clarin.eu/ds/ComponentRegistry#/?itemId=clarin.eu%3Acr1%3Ac_1407745712014&registrySpace=public

but both options are presented to the user in the CMDI Maker.
"Unkown" is the default value. Everyone who leaves the default value in place will produce invalid XML

**Comment by jblumtritt** [comment]
it should be possible to leave the field empty. In this case the element "Continent" has to be removed from the output because it must not be empty.

**Comment by MigRam** [comment]
solve #18

**Comment by jblumtritt** [comment]
There are still multiple problems with "Continent". 

> Value '' is not facet-valid with respect to enumeration '[AF, EU, AS, NA, SA, OC, AN]'. It must be a value from the enumeration.
1. the element must not be empty but one of the values above. This is not a valid output: <code>&lt;continent/&gt;</code> because it's an empty element. i suggest to simply remove it if there is no input.
2. currently I get results in the form of <code>&lt;Continent&gt;Africa&lt;/Continent&gt;</code>. Should be one of those values above = AF.
3. "Middle-America" has no counterpart in the list.

sources:
https://catalog.clarin.eu/ds/ComponentRegistry#/?itemId=clarin.eu%3Acr1%3Ac_1407745712014&registrySpace=public

**Comment by MigRam** [comment]
Hi,

ok danke. DA die XML output keine Fehler ausgibt, dachte ich das dies 
auch geht.

Gut dann muss man eine Lösung finden, dass die Werte [AF, EU, AS, NA, 
SA, OC, AN] in <Continent> ausgibt.

Gruss
Miguel

Am 16.06.2016 um 15:17 schrieb Jonathan Blumtritt:

**Comment by MigRam** [comment]
closed #25
