### ISSUE TITLE
Fields are not exported to XML

### ISSUE THREAD

**Issue by fxru** [cceh/ELDP-Environment-for-CMDI-Maker#2]
The fields

"Recording Equipment"
"Recording Conditions"
"Continent"

are not exported to CMDI-XML, but should be.

The field "region" is not exported, but also doesn’t correspond to a category in ELDP-CMDI, so it should be eliminated from the interface.

(Bug #2167 in Redmine)

**Comment by MigRam** [comment]
Solved #15
