### ISSUE TITLE
ELDP: ELDP Environment doesn't treat .tiff-files as image files in the XML-output

### ISSUE THREAD

**Issue by jblumtritt** [cceh/ELDP-Environment-for-CMDI-Maker#8]
![cmdi-maker-tiffs_1](https://cloud.githubusercontent.com/assets/3205396/14752976/9366fbf6-08d2-11e6-91f8-efa1401a5051.jpg)
![cmdi-maker-tiffs_2](https://cloud.githubusercontent.com/assets/3205396/14752977/93715718-08d2-11e6-80e4-f6997f1b2eae.jpg)

**Comment by MigRam** [comment]
This issue could not be confirmed because ELDP recognizes Tiff files on Master and Beta ELDP v1.11.
ELDP Test-Tiff File on XML Output display.

**Comment by polyrainbow** [comment]
I can confirm this issue. It happens because there's an entry for .tiff files missing here:
https://github.com/cceh/ELDP-Environment-for-CMDI-Maker/blob/e015a15576773299f33ec86ef1591726f5a2a541/src/js/eldp_generator.js#L454-L480
Can be fixed quickly.

**Comment by jblumtritt** [comment]
thanks, *.tif is now recognised. can you please also add *.tiff extension?
